/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mini.project;

public class App {
  public static String getGreeting() {
    return "Hello apple.";
  }

  public static void main(String[] args) {
    System.out.println(getGreeting());
    System.out.println("  ,--./,-.");
    System.out.println(" / #      \\");
    System.out.println("|          |");
    System.out.println(" \\        / ");
    System.out.println("  `._,._,'");
  }
}
